name: Build Bloom
on: [push]
jobs:
  paperclip:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
      - name: Setup Java 21
        uses: actions/setup-java@v3.11.0
        with:
          java-version: "21"
          cache: "gradle"
          distribution: "temurin"
      - name: Permission gradlew
        run: chmod +x gradlew
      - name: Configure Git User
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: ApplyPatches
        run: ./gradlew applyPatches --stacktrace
      - name: Build Paperclip jar
        run: ./gradlew createReobfPaperclipJar --stacktrace
      - name: Upload Paperclip jar
        uses: actions/upload-artifact@v2
        with:
          name: Bloom.jar
          path: build/libs/Bloom-paperclip-*-reobf.jar